### ISSUE TITLE
po zalogowniu się jako pracownik nie można dodawać kursów

### ISSUE THREAD

**Issue by rnowakpw** [ianczyko/assigner#24]
![Zrzut ekranu z 2024-02-26 10-40-40](https://github.com/ianczyko/assigner/assets/105272394/b5cb8add-0f66-4dac-b031-5c3f71a5f364)

**Comment by ianczyko** [comment]
Wynika to z rozróżnienia ról nauczyciel / koordynator. Zamysł był aby tworzenie kursów było przeznaczone jedynie dla wyznaczonych nauczycieli.

**Comment by rnowakpw** [comment]
Rozumiem, popieram. Pozdr. Robert Nowak
Igor Anczykowski ***@***.***> writes:

> Wynika to z rozróżnienia ról nauczyciel / koordynator. Zamysł był aby tworzenie kursów było przeznaczone jedynie dla wyznaczonych nauczycieli.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

-- 
Robert Nowak, DSc PhD MSc(CS)
email: ***@***.***
http://staff.elka.pw.edu.pl/~rnowak2
Institute of Computer Science, Warsaw University of Technology
Nowowiejska 15/19, room 23, 00-665 Warsaw, Poland

**Comment by rnowakpw** [comment]
proszę zamknąć to isssue
