### ISSUE TITLE
Ręczne przypisywanie

### ISSUE THREAD

**Issue by rbiedrzy** [ianczyko/assigner#37]
Sustem powinien umożliwiać ręczne przypisywanie zespołów. Przykładowy scenariusz- zespół zgłasza się z własnym tematem, czy zespół przekonuje prowadzącego że dany temat zrealizuje ze szczególnym zaangazowaniem.

**Comment by ianczyko** [comment]
Funkcjonalność taka istnieje, można ręcznie przypisać zespół do tematu będąc na ekranie zespołu:
![image](https://github.com/ianczyko/assigner/assets/56764244/e2421730-b86a-4f63-860f-9e7980b5a9f3)
