### ISSUE TITLE
eksport wyników przypisania

### ISSUE THREAD

**Issue by rnowakpw** [ianczyko/assigner#42]
eksport wyników przypisania, aby można było używać z innymi narzędziami,

np. plik csv zawierający usos id studenta

**Comment by rbiedrzy** [comment]
Ja bym preferował tak: Eksport wyników zapisów do formatu tekstowego w postaci 3 kolumn: Nazwa tematu; Nazwisko i imię członka#1; Nazwisko i imię członka#2

**Comment by rnowakpw** [comment]
tutaj się zgadzam, separatorami mogą być średniki. Do tego co pisze Rafał proszę dodać usos id, bo wtedy można będzie też ładować do USOS-a (chociaż teraz nie wiem po co)

**Comment by ianczyko** [comment]
Z racji na to, że system wspiera zespoły o dowolnych rozmiarach, został przyjęty następujący format eksportu:

|user_usos_id|user_name                    |user_surname|team_id                                      |team_name|assigned_project_id|assigned_project_name|is_assignment_final|happiness|
|------------|-----------------------------|------------|---------------------------------------------|---------|-------------------|---------------------|-------------------|---------|
|11111      |Name1                        |Surname1    |1                                            |team1    |1                  |poject1              |FALSE              |3        |
|22222       |Name2                        |Surname2    |1                                            |team1    |1                  |poject1              |FALSE              |3        |
|33333       |Name3                        |Surname3    |2                                            |team2    |2                  |project2             |FALSE              |4        |


[assigner_export_example.csv](https://github.com/ianczyko/assigner/files/14547243/assigner_export_example.csv)

**Comment by ianczyko** [comment]
Poprawki zostały wdrożone na serwer ii.
