### ISSUE TITLE
Brak możliwości utworzenia zespołu

### ISSUE THREAD

**Issue by rmako** [ianczyko/assigner#48]
Nie posiadam możliwości utworzenia zespołu, mimo dostępu do kursu UMA 24L. Nie mam również możliwości dołączenia do zespołu. Proszę o weryfikację.
01109088@pw.edu.pl
<img width="807" alt="Zrzut ekranu 2024-03-12 083522" src="https://github.com/ianczyko/assigner/assets/151464443/656e6197-57c7-4113-9e33-7f7194c44f2e">

**Comment by rmako** [comment]
czy problem może wynikać z faktu, że w grupie znajduje się osoba o takim samym nazwisku (w kolejności alfabetycznej ta osoba jest przed mną)

**Comment by ianczyko** [comment]
USOS wykrył u Pana rolę "nauczyciel". Zakładam, że w kontekście zapisów na UMA jest to błąd, ustawię Panu niższą rolę (student) ręcznie.

**Comment by rmako** [comment]
Takz jestem w usosie zarówno studentem jak i nauczycielem.
W UAM jako student.

Dziękuję

pt., 15 mar 2024, 15:05 użytkownik Igor Anczykowski <
***@***.***> napisał:
